audit_header: false
title: "Coppell's Best Real Estate Training"
description: Maria DiPoce, a top Real Estate Agent in Coppell, shares her own internal real estate agent training for free. Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: https://coppell.yourkwoffice.com/mcj/user/CareerFormGetAction.do
  - title: Events
    url: https://www.eventbrite.com/o/maria-dipoce-team-leaderceo-kw-dfw-preferred-20180364588
  - title: Free Strategy Call
    url: https://careers.kw.com/tx-dfw-preferred-296/contact/
client:
  name: Maria DiPoce
  title:
  license_number:
  about_markdown: |
    Maria DiPoce has been in the real estate industry for the past 14 years. She started as an investor and then moved on to being a traditional real estate agent. She has a background in network marketing and is the driver and visionary of this office. Since she was hired on in March of 2017 the office has grown 33% in agent count, 13% in volume and 9.9% in units sold. She is passionate about helping people follow their dreams and achieve their goals.
  market: Coppell
  brand: Keller Williams DFW Preferred
  brokerage:
  address: 546 East Sandy Lake Rd. suite 100A Coppell TX 75019
  phone: 972-350-5003
  phone_type:
  phone2:
  phone2_type:
  email: mariadipoce@kw.com
  url: http://kwdfwpreferred.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Keller Williams DFW Preferred can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KWDFWPreferred
  linkedin_url: https://www.linkedin.com/in/mariadipoce/
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/kwri
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Coppell Real Estate Podcast with Maria DiPoce'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Coppell Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams DFW Preferred - your professional Coppell Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Coppell, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Maria DiPoce'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Coppell Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2cdbe9'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
